services:
  # MySQL DB
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qwerty123
      MYSQL_DATABASE: yourdb
      MYSQL_PASSWORD: qwerty123
    networks:
      - mysql-phpmyadmin
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
      timeout: 20s
      retries: 10

  # PhpMyAdmin
  phpmyadmin:
    depends_on:
      db:
        condition: service_healthy
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_PASSWORD: qwerty123
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:

volumes:
  db_data:
